name: Automated Linters

on: pull_request

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest # sistema onde sera rodado
    steps:
      - uses: actions/checkout@v4 #actions sao extensoes
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: yarn install --frozen-lockfile # garante as dependencias do yarn.lock
      - run: yarn lint:prettier:check
      - run: yarn lint
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest # sistema onde sera rodado
    steps:
      - uses: actions/checkout@v4 #actions sao extensoes
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: yarn install --frozen-lockfile # garante as dependencias do yarn.lock
      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
