name: Automated Linters

on: pull_request

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest # sistema onde sera rodado
    steps:
      - uses: actions/checkout@v4 #actions sao extensoes
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: yarn install --frozen-lockfile # garante as dependencias do yarn.lock
      - run: yarn lint:prettier:check
      - run: yarn lint
